# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/hello.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class TaskState(betterproto.Enum):
    """
    Style guide prefers prefixing enum values instead of surrounding with an
    enclosing message
    """

    TASK_OPEN = 0
    TASK_IN_PROGRESS = 1
    TASK_POST_PONED = 2
    TASK_CLOSED = 3
    TASK_DONE = 4


@dataclass
class TodoList(betterproto.Message):
    owner_id: int = betterproto.int32_field(1)
    owner_name: str = betterproto.string_field(2)
    todos: List["TodoListListItems"] = betterproto.message_field(3)


@dataclass
class TodoListListItems(betterproto.Message):
    state: "TaskState" = betterproto.enum_field(1)
    task: str = betterproto.string_field(2)
    due_date: str = betterproto.string_field(3)
